### PR TITLE
fix: Enable Source-Tracking Commands (Push*, Pull*, View Changes*) for Source-Tracked Sandboxes

### LINKED ISSUE #2952: Setting to change to pull/push operations in context menu for source-tracked Sandboxes
I am currently finding my way around source-tracking on Sandboxes, which I think is an amazing feature, however I am finding it hard currently to change the workflow that I (and many others) have gotten used to: Deploying / Pushing on Save and using the Command Palette for everything else.

If I am not mistaken, Auth with a Sandbox will always give you Deploy and Retrieve commands, both in the Command Palette and the context menu currently. Does not matter if the Sandbox is source-tracked or not. That means in order to get to the push/pull commands, I always have to go to the Terminal and type in what I want to do. That is definitely possible, will however hamper acceptance among colleagues. 

Is it feasible to detect a source-tracked Sandbox and enable push/pull accordingly in the command palette? If not that, maybe a setting that we could use on the workspace-level would help.

In the fear of repeating something everyone already knows: I have updated the CLI and checked everywhere I thought logical, didn't find anything regarding this issue however.

Thanks in advance.

### PR DESCRIPTION
**Pull request by klewis-sfdc**
### What does this PR do?
* Fixes the getWorkspaceOrgType function to properly identify source-tracked sandboxes as being source-tracking enabled.  
* Making this change exposes the SFDX: Push*, SFDX: Pull*, and SFDX: View Changes* commands when connected to a source-tracked sandbox org.  These commands have been slightly renamed, to remove the word "Scratch" from the command title.

* ⚠️ This PR changes the behavior of the `Push-or-deploy-on-save` setting.  Prior to this PR, this setting would initiate a `deploy` operation on save.  After this PR the setting will initiate a `push` operation on save - since the extension code now recognizes a sandbox with source-tracking enabled as being a source-tracked org.  ⚠️ 

### What issues does this PR fix or reference?
@W-12757190@
Fixes #2952

Many thanks to @FabienTaillon for submitting a draft PR (#4727) to implement this.

### Functionality Before
* getWorkspaceOrgType would return OrgType.NonSourceTracked for a source-tracked Sandbox.
* When enabled, the Push-or-deploy-on-save setting would initiate a `deploy` operation on save.
* The following commands were not exposed when connected to a source-tracked Sandbox:
    'SFDX: Pull Source from Default Scratch Org',
    'SFDX: Pull Source from Default Scratch Org and Override Conflicts',
    ~~'SFDX: Pull Source from Default Scratch Org (Legacy)',~~**
    ~~'SFDX: Pull Source from Default Scratch Org and Override Conflicts (Legacy)',~~**

    'SFDX: Push Source to Default Scratch Org',
    'SFDX: Push Source to Default Scratch Org and Override Conflicts',
    ~~'SFDX: Push Source to Default Scratch Org (Legacy)',~~**
    ~~'SFDX: Push Source to Default Scratch Org and Override Conflicts (Legacy)',~~**

    'SFDX: View Local Changes',
    'SFDX: View Changes in Default Scratch Org',
    'SFDX: View All Changes (Local and in Default Scratch Org)',
    ~~'SFDX: View All Changes (Local and in Default Scratch Org) (Legacy)'~~**

Note: the "(Legacy)" commands were removed in #4771 

### Functionality After
* getWorkspaceOrgType returns OrgType.SourceTracked for a source-tracked Sandbox.
* When enabled, the Push-or-deploy-on-save setting initiates a `push` operation on save.
* The following commands ARE exposed when connected to a source-tracked Sandbox (and are renamed slightly):
    'SFDX: Pull Source from Default Org',
    'SFDX: Pull Source from Default Org and Override Conflicts',

    'SFDX: Push Source to Default Org',
    'SFDX: Push Source to Default Org and Override Conflicts',

    'SFDX: View Local Changes',
    'SFDX: View Changes in Default Org',
    'SFDX: View All Changes (Local and in Default Org)',

**Todos:**
- [x] Check for behavioral changes re: the push-or-deploy-on-save setting
- [x] Keep Deploy* and Retrieve* commands exposed for source-tracked sandboxes to keep existing behavior consistent.  These commands are being updated to handle source-tracking in #4597

### CODE REVIEW

File: packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts [hunk 1]
```diff
@@ -4,31 +4,30 @@
...
-  const isScratchOrg = await OrgAuthInfo.isAScratchOrg(username).catch(err =>
-    telemetryService.sendException(
-      'get_workspace_org_type_scratch_org',
-      err.message
-    )
-  );
-  return isScratchOrg ? OrgType.SourceTracked : OrgType.NonSourceTracked;
+/**
+ * @description determines whether the default org is source-tracked or not.
+ * During dev it was observed that that were some potential issues with other options
```
Comment (jeffb-sfdc) [inline packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts:20]: "that that" - typo?  Maybe you meant "that there"?

**Comment by klewis-sfdc** [comment]
@sbudhirajadoc and @AnanyaJha FYI - realized that this workspaceOrgType change also exposes the SFDX: View Changes* commands - which is good since those commands can be used to check source status in a source-tracked sandbox now.  Just wanted to give you a heads up that I also updated the title text for those commands to remove "Scratch".

File: packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts [hunk 2]
```diff
@@ -39,7 +38,7 @@ export function setWorkspaceOrgTypeWithOrgType(orgType: OrgType) {
 export async function setupWorkspaceOrgType(defaultUsernameOrAlias?: string) {
   try {
     setHasDefaultUsername(!!defaultUsernameOrAlias);
-    const orgType = await getWorkspaceOrgType(defaultUsernameOrAlias);
+    const orgType = await getWorkspaceOrgType();
```
Comment (jeffb-sfdc) [inline packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts:41]: On line 77, there is:
```
'sfdx:default_username_has_no_change_tracking',
```

Should it be
```
sfdx:default_username_has_no_change_tracking || !sfdx:is_scratch_org
```
(like that in packages/salesforcedx-vscode-core/package.json?)

I don't know if it should or not, but I saw this here, and saw that the other instances of `sfdx:default_username_has_no_change_tracking` was changed to also check for !is_scratch_org and was wondering if this needs to be updated as well.

File: packages/salesforcedx-vscode-core/src/context/workspaceContext.ts [hunk 3]
```diff
@@ -59,3 +63,16 @@ export class WorkspaceContext {
     return WorkspaceContextUtil.getInstance().alias;
   }
 }
+
+async function setIsScratchOrg() {
+  const username = await ConfigUtil.getUsername();
+  if (!username) {
+    return;
+  }
+  const isScratch = await OrgAuthInfo.isAScratchOrg(String(username));
```
Comment (jeffb-sfdc) [inline packages/salesforcedx-vscode-core/src/context/workspaceContext.ts:72]: Two comments:
1. `username` was already check for being undefined in line 69.  Because of this, the `String()` on line 72 isn't needed.
2. nit-pick: my preference is to not abbreviate variable names, and pref it named, `isScratchOrg`

File: packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts [hunk 4]
```diff
@@ -4,31 +4,30 @@
...
+ * @description determines whether the default org is source-tracked or not.
+ * During dev it was observed that there were some potential issues with other options
+ * (org.isScratch, org.tracksSource) related to cache-ing and a newly created
+ * Scratch Org would sometimes return false.  Using org.supportsSourceTracking()
+ * because it has been the most consistently accurate solution here.
+ * @returns OrgType (SourceTracked or NonSourceTracked) of the current default org
+ */
+export async function getWorkspaceOrgType(): Promise<OrgType> {
+  const connection = await WorkspaceContext.getInstance().getConnection();
+  const org: Org = await Org.create({ connection });
```
Comment (jeffb-sfdc) [inline packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts:28]: On line 28, the type definition comes from `Org.create()`, and the `: Org` isn't needed.  preferred change would be:

`const org = await Org.create({ connection });`

File: packages/salesforcedx-vscode-core/src/settings/pushOrDeployOnSave.ts [hunk 5]
```diff
@@ -73,15 +73,7 @@ export class DeployQueue {
...
-        let defaultUsernameorAlias: string | undefined;
-        if (workspaceUtils.hasRootWorkspace()) {
-          defaultUsernameorAlias = await OrgAuthInfo.getDefaultUsernameOrAlias(
-            false
-          );
-        }
-        const orgType = await workspaceContextUtils.getWorkspaceOrgType(
-          defaultUsernameorAlias
-        );
+        const orgType = await workspaceContextUtils.getWorkspaceOrgType();
```
Comment (jeffb-sfdc) [inline packages/salesforcedx-vscode-core/src/settings/pushOrDeployOnSave.ts:76]: On line 19, the import of OrgAuthInfo and workspaceUtils aren't needed and line 19 can be removed.

Comment (jeffb-sfdc) [inline packages/salesforcedx-vscode-core/src/settings/pushOrDeployOnSave.ts:76]: Comment: nice cleanup!  (lines 76-84 in previous version into `workspaceContextUtils.getWorkspaceOrgType()`)

File: packages/salesforcedx-vscode-core/test/jest/context/workspaceContext.test.ts [hunk 6]
```diff
@@ -0,0 +1,9 @@
+describe('workspaceContext', () => {
+  describe('handleCliConfigChange', () => {
+    it('should update context variables and UI elements when the config file changes', () => {});
```
Comment (jeffb-sfdc) [inline packages/salesforcedx-vscode-core/test/jest/context/workspaceContext.test.ts:3]: These are coming in a follow up PR?

File: packages/salesforcedx-vscode-core/test/vscode-integration/context/workspaceOrgType.test.ts [hunk 7]
```diff
@@ -86,116 +93,47 @@ describe('workspaceOrgType unit tests', () => {
...
-          devHubUsername: devHubUser
-        })
+      orgCreateStub.resolves({
+        supportsSourceTracking: async () => true
       });
 
-      const orgType = await workspaceContextUtils.getWorkspaceOrgType(
-        defaultUsername
-      );
+      const orgType: OrgType = await workspaceContextUtils.getWorkspaceOrgType();
```
Comment (jeffb-sfdc) [inline packages/salesforcedx-vscode-core/test/vscode-integration/context/workspaceOrgType.test.ts:101]: The "`: OrgType`" isn't needed.

File: packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts (hunk 2 above)
Comment (klewis-sfdc) [reply packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts:41]: The change in package.json to include "!is_scratch_org" is so that the deploy and retrieve commands are still exposed for src-trk sandboxes (but not yet for scratch orgs).  

Here the code is simply setting whether or not the current ordered has change/source tracking.  So !is_scratch_org is not needed here. 

And the is_scratch_org context var is being set now in workspaceContext.

File: packages/salesforcedx-vscode-core/test/jest/context/workspaceContext.test.ts (hunk 6 above)
Comment (klewis-sfdc) [reply packages/salesforcedx-vscode-core/test/jest/context/workspaceContext.test.ts:3]: I'm hoping to get them in this one. Working on them now.

File: packages/salesforcedx-vscode-core/package.json [hunk 8]
```diff
@@ -150,14 +150,14 @@
         {
           "id": "metadata",
           "name": "Metadata",
-          "when": "sfdx:project_opened && sfdx:default_username_has_no_change_tracking"
+          "when": "sfdx:project_opened && (sfdx:default_username_has_no_change_tracking || !sfdx:is_scratch_org)"
```
Comment (klewis-sfdc) [inline packages/salesforcedx-vscode-core/package.json:153]: Had to add this context variable in order to keep the Deploy* and Retrieve* commands exposed for source-tracked Sandboxes but not yet expose them for Scratch Orgs.

File: packages/salesforcedx-vscode-core/src/context/contextVariables.ts [hunk 9]
```diff
@@ -0,0 +1,22 @@
...
+ * Copyright (c) 2023, salesforce.com, inc.
+ * All rights reserved.
+ * Licensed under the BSD 3-Clause license.
+ * For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
+ */
+import { ConfigUtil } from '@salesforce/salesforcedx-utils-vscode';
+import * as vscode from 'vscode';
+import { OrgAuthInfo } from '../util';
+
+export async function setIsScratchOrg() {
```
Comment (klewis-sfdc) [inline packages/salesforcedx-vscode-core/src/context/contextVariables.ts:11]: Pulled this out from workspaceContext to make testing easier.

File: packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts [hunk 10]
```diff
@@ -56,6 +55,10 @@ export async function setupWorkspaceOrgType(defaultUsernameOrAlias?: string) {
           setDefaultUsernameHasChangeTracking(false);
           setDefaultUsernameHasNoChangeTracking(false);
           break;
+        case 'NoUsernameFoundError':
```
Comment (klewis-sfdc) [inline packages/salesforcedx-vscode-core/src/context/workspaceOrgType.ts:58]: Saw this error when I was writing the unit test.

File: packages/salesforcedx-vscode-core/package.json (hunk 8 above)
Comment (AnanyaJha) [reply packages/salesforcedx-vscode-core/package.json:153]: Do the deploy/retrieve commands not yet work for scratch orgs?

**Review by AnanyaJha — APPROVED** [review]
:shipit:

File: packages/salesforcedx-vscode-core/package.json (hunk 8 above)
Comment (klewis-sfdc) [reply packages/salesforcedx-vscode-core/package.json:153]: They work to deploy and retrieve the components, but they do not fix up source tracking correctly, since they don't have the source tracking library in the flow.  

I broke the original PR up to split out the work in this PR, and the next two PRs will be to "fix Retrieve for source-tracked sandboxes" (to add in STL #4773), and then  "fix Deploy for source-tracked sandboxes" (to add in STL).  

After those two, we will expose deploy/retrieve for Scratch orgs (now that they will be handling source tracking correctly).  And finally, expose Org Browser.

File: packages/salesforcedx-vscode-core/test/jest/context/contextVariables.test.ts [hunk 11]
```diff
@@ -0,0 +1,56 @@
...
+
+    beforeEach(() => {
+      getUsernameMock = jest
+        .spyOn(ConfigUtil, 'getUsername')
+        .mockResolvedValue('test@test.com');
+
+      isAScratchOrgMock = jest.spyOn(OrgAuthInfo, 'isAScratchOrg');
+
+      executeCommandSpy = jest.spyOn(vscode.commands, 'executeCommand');
+    });
```
Comment (jeffb-sfdc) [inline packages/salesforcedx-vscode-core/test/jest/context/contextVariables.test.ts:26]: With Jest, if I remember correctly the mocks and spies should be cleared after each test:
```
afterEach(() => {
  jest.clearAllMocks();
}
```

File: packages/salesforcedx-vscode-core/test/jest/context/workspaceContext.test.ts [hunk 12]
```diff
@@ -0,0 +1,51 @@
...
+ */
+import { WorkspaceContextUtil } from '@salesforce/salesforcedx-utils-vscode';
+import { WorkspaceContext, workspaceContextUtils } from '../../../src/context';
+import * as contextVariables from '../../../src/context/contextVariables';
+import { decorators } from '../../../src/decorators';
+
+describe('workspaceContext', () => {
+  let setupWorkspaceOrgTypeMock: jest.SpyInstance;
+  let workspaceContextUtilGetInstanceSpy: jest.SpyInstance;
+  let setIsScratchOrgSpy: jest.SpyInstance;
```
Comment (jeffb-sfdc) [inline packages/salesforcedx-vscode-core/test/jest/context/workspaceContext.test.ts:15]: Since setIsScratchOrgSpy and decoratorsMock aren't created in this describe/beforeEach,  to scope them they should probably be moved to line 35.

Also, as I mentioned earlier, `clearAllMocks()` should be called in `afterEach()`, but with these split like they are, I'm not sure where the best place to call `clearAllMocks()` would be.

File: packages/salesforcedx-vscode-core/test/jest/context/contextVariables.test.ts (hunk 11 above)
Comment (klewis-sfdc) [reply packages/salesforcedx-vscode-core/test/jest/context/contextVariables.test.ts:26]: Jest has some cool config options, so this is already done via a jest config setting in the VSCE repo.

Each package contains a jest.config.js file, which imports from the top-level jest.base.config file:



In that file the [resetMocks option](https://jestjs.io/docs/configuration#clearmocks-boolean) is set to true, which makes jest call clearAllMocks before each test:

**Review by jeffb-sfdc — APPROVED** [review]

**Comment by jeffb-sfdc** [comment]
I QA'd this and didn't find any issues.  I tested push, pull, and view changes on a scratch org, a source tracked sandbox org, and tests deploy & retrieve on a (non-source tracked) sandbox org.
