### PR TITLE
fix: check for expiration of default org on activation

### LINKED ISSUE #5506: Missing Label when folder is not SFDX
### Summary

When a project is not sfdx (missing `sfdx-project.json`), the warning message does not display the text, instead it shows that a label containing a target text is missing.

### Steps To Reproduce:

1.  Create an sfdx project
2. Delete `sfdx-project.json` file
3. Try running retrieve or any other sfdx command via VScode

### Expected result

A meaningful message shows up signalizing that the folder is not sfdx-like or sfdx-project.json file is missing

### Actual result

The notification contains a warning message about missing label

image

**Salesforce Extension Version in VS Code**:
Salesforce CLI Integration v60.2.3

**SFDX CLI Version**:
@salesforce/cli/2.28.6 darwin-arm64 node-v20.11.1

**OS and version**:
Mac OS 14.3.1 (23D60)

**VS Code version**:
1.87.1

### PR DESCRIPTION
**Pull request by CristiCanizales**
### What does this PR do?
- Adds check to verify during activation if default org is expired, and if so sends a notification to the user.
- Changes icon to ⚠️ in status bar item if default org is expired 
- Changes icon to ❌  in status bar if default org in config file is not valid
- New Jest test files for `orgList.ts` and `orgUtil.ts`
- Adds no salesforce project opened label to the right i18n.ts file to fix #5506  

### What issues does this PR fix or reference?
@W-16494805@
@W-15261166@
#5506 

### Functionality After
- Notification on activation if default org is expired
- Warning icon on status bar item if default org is expired
- Error icon on status bar item if default org is not valid
-  Right message in notification for no salesforce project opened

image
image
image

### CODE REVIEW

File: packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts [hunk 1]
```diff
@@ -37,7 +41,20 @@ export class OrgList implements vscode.Disposable {
...
+        .then(isExpired => {
+          if (isExpired) {
+            this.statusBarItem.text = `$(warning) ${targetOrgOrAlias}`;
+          } else {
+            this.statusBarItem.text = `$(plug) ${targetOrgOrAlias}`;
+          }
+        })
+        .catch(error => {
+          if (error.name === 'NamedOrgNotFoundError') {
+            this.statusBarItem.text = '$(error) Default org is not valid';
```
Comment (CristiCanizales) [inline packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts:54]: @sbudhirajadoc Could I please get a review for this text? 🙂

File: packages/salesforcedx-vscode-core/src/messages/i18n.ts [hunk 2]
```diff
@@ -282,6 +282,7 @@ export const messages = {
   org_select_text: 'Select an org to set as default',
   org_expired: 'Expired',
   missing_default_org: 'No Default Org Set',
+  default_org_expired: 'Your default org is expired.',
```
Comment (CristiCanizales) [inline packages/salesforcedx-vscode-core/src/messages/i18n.ts:285]: @sbudhirajadoc and for this one. This is for the warning notification

File: packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts (hunk 1 above)
Comment (CristiCanizales) [reply packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts:54]: image

File: packages/salesforcedx-vscode-core/src/messages/i18n.ts (hunk 2 above)
Comment (sbudhirajadoc) [reply packages/salesforcedx-vscode-core/src/messages/i18n.ts:285]: Your default org has expired. Select a new Salesforce org as your default org try again.

Comment (CristiCanizales) [reply packages/salesforcedx-vscode-core/src/messages/i18n.ts:285]: image

File: packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts (hunk 1 above)
Comment (sbudhirajadoc) [reply packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts:54]: The org you’ve chosen as your default org isn’t valid. Choose a differnt default org and try again.

File: packages/salesforcedx-vscode-core/src/messages/i18n.ts (hunk 2 above)
Comment (sbudhirajadoc) [reply packages/salesforcedx-vscode-core/src/messages/i18n.ts]: final -- Your default org has expired. Some of the the command palette commands may not longer work. Try switching your default org and try again.

File: packages/salesforcedx-vscode-core/test/jest/orgPicker/orgList.test.ts [hunk 3]
```diff
@@ -0,0 +1,334 @@
...
+      const orgAuths = [orgAuth];
+      getAuthFieldsForMock.mockResolvedValueOnce({
+        scratchAdminUsername: 'admin@example.com'
+      } as AuthFields);
+      getDevHubUsernameMock.mockResolvedValueOnce(null);
+
+      const result = await orgList.filterAuthInfo(orgAuths);
+
+      expect(result).toEqual([]);
+    });
```
Comment (daphne-sfdc) [inline packages/salesforcedx-vscode-core/test/jest/orgPicker/orgList.test.ts:114]: Why do we want to filter out scratch orgs with the `scratchAdminUsername` field?  What's special about them?

Comment (CristiCanizales) [reply packages/salesforcedx-vscode-core/test/jest/orgPicker/orgList.test.ts:114]: I don't know, most of these tests were in mocha and I just translated them to jest

File: packages/salesforcedx-vscode-core/test/jest/util/orgUtil.test.ts
Comment (daphne-sfdc) [inline packages/salesforcedx-vscode-core/test/jest/util/orgUtil.test.ts:1]: Is it possible to add another test case for the presence of both an expired org and an org that is about to expire?  The test should check for the presence of 2 warning notifications.

File: packages/salesforcedx-vscode-core/test/vscode-integration/util/orgUtil.test.ts [hunk 4]
```diff
@@ -70,15 +70,15 @@ describe('orgUtil tests', () => {
...
       ]);
       const orgList = new OrgList();
-      await checkForExpiredOrgs(orgList);
+      await checkForSoonToBeExpiredOrgs(orgList);
 
       expect(showWarningMessageSpy.called).to.equal(false);
       expect(appendLineSpy.called).to.equal(false);
       expect(showChannelOutputSpy.called).to.equal(false);
-      expect(authInfoCreateStub.called).to.equal(false);
+      expect(authInfoCreateStub.called).to.equal(true);
```
Comment (daphne-sfdc) [inline packages/salesforcedx-vscode-core/test/vscode-integration/util/orgUtil.test.ts:78]: Why is this changed from false to true?  I see that Line 90 of OrgUtil.test.ts (the unit test for only dev hubs) seems to be a similar case to this line, and it says `expect(authInfoCreateSpy).not.toHaveBeenCalled();`

File: packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts [hunk 5]
```diff
@@ -50,6 +50,9 @@ export class OrgList implements vscode.Disposable {
           }
         })
         .catch(error => {
+          if (error.name === 'NamedOrgNotFoundError') {
+            this.statusBarItem.text = '$(error) Default org is not valid';
```
Comment (diyer) [inline packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts]: @sbudhirajadoc can you please review this text?

File: packages/salesforcedx-vscode-core/src/messages/i18n.ja.ts [hunk 6]
```diff
@@ -243,6 +243,10 @@ export const messages = {
     'ソースをデプロイまたは取得中にエラー: デプロイまたは取得しようとしたファイルかディレクトリが sfdx-project.json ファイルで指定されたパッケージディレクトリにありません。この場所を "packageDirectories" の値に追加するか、異なるファイルやディレクトリをデプロイまたは取得してください。sfdx-project.json についての詳細は https://developer.salesforce.com/docs/atlas.ja-jp.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm を参照してください。',
   org_select_text: 'デフォルトに設定する組織を選択',
   missing_default_org: 'デフォルトの組織が未設定',
+  invalid_default_org:
+    'The org you’ve chosen as your default org isn’t valid. Please choose a different one.',
```
Comment (diyer) [inline packages/salesforcedx-vscode-core/src/messages/i18n.ja.ts:247]: cc: @sbudhirajadoc

File: packages/salesforcedx-vscode-core/src/messages/i18n.ts [hunk 7]
```diff
@@ -282,6 +282,10 @@ export const messages = {
   org_select_text: 'Select an org to set as default',
   org_expired: 'Expired',
   missing_default_org: 'No Default Org Set',
+  invalid_default_org:
+    'The org you’ve chosen as your default org isn’t valid. Please choose a different one.',
```
Comment (diyer) [inline packages/salesforcedx-vscode-core/src/messages/i18n.ts:286]: what is an invalid org ?

Comment (daphne-sfdc) [reply packages/salesforcedx-vscode-core/src/messages/i18n.ts:286]: I think of an "invalid org" as one that isn't able to be used.  So it would be either an expired or deleted org.

File: packages/salesforcedx-vscode-core/test/vscode-integration/util/orgUtil.test.ts (hunk 4 above)
Comment (CristiCanizales) [reply packages/salesforcedx-vscode-core/test/vscode-integration/util/orgUtil.test.ts:78]: It should have been called, but I guess this file is outdated. I'll delete it since I covered all the cases present in the jest test file.

File: packages/salesforcedx-vscode-core/src/messages/i18n.ts (hunk 7 above)
Comment (diyer) [reply packages/salesforcedx-vscode-core/src/messages/i18n.ts:286]: Thanks Daphne. why are we differentiation this and the following use case and giving different error message to the user?

**Review by daphne-sfdc — APPROVED** [review]
Approved! 🎉 

Test plan here: https://salesforce.quip.com/w0ZmAIiAnpIt ✅

File: packages/salesforcedx-vscode-core/src/messages/i18n.ts (hunk 7 above)
Comment (CristiCanizales) [reply packages/salesforcedx-vscode-core/src/messages/i18n.ts:286]: An invalid org is something you type in the config file that is not an org you have in the cli

Comment (diyer) [reply packages/salesforcedx-vscode-core/src/messages/i18n.ts:286]: thanks Cristi. It seems weird that we show an invalid org in the org picker. Shouldn't we even let that to happen?

Comment (CristiCanizales) [reply packages/salesforcedx-vscode-core/src/messages/i18n.ts:286]: We will not show it there, we will show the message. There's a screenshot in Daphne's test doc, like the last one in the pr description (that was before sonal's text review)

File: packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts [hunk 8]
```diff
@@ -37,7 +41,22 @@ export class OrgList implements vscode.Disposable {
 
   private displayTargetOrg(targetOrgOrAlias?: string) {
     if (targetOrgOrAlias) {
-      this.statusBarItem.text = `$(plug) ${targetOrgOrAlias}`;
+      return Promise.resolve(this.isOrgExpired(targetOrgOrAlias))
+        .then(isExpired => {
+          if (isExpired) {
+            this.statusBarItem.text = `$(warning) ${targetOrgOrAlias}`;
```
Comment (diyer) [inline packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts:47]: we are showing invalid org as a error but expired org as a warning, why is that?

Comment (sbudhirajadoc) [reply packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts:47]: Final? -- Your default org has expired. Some of the command palette commands may no longer work. Switch your default org and try again.

Comment (CristiCanizales) [reply packages/salesforcedx-vscode-core/src/orgPicker/orgList.ts:47]: Because right now we just want to let users know that it's expired, but we haven't decided what we'll do with expired orgs in general. - We'll decide that after discussing Pete's spike.

It's like the notification on activation if the default org you had set is expired, it's just a warning notification.
