### PR TITLE
fix: metadata xml issues by removing tooling retrieve

### LINKED ISSUE #3124: Xml file content is missing label tag with the new Experimental Deploy Retrieve
### Summary

With the 2 Experimental Deploy Retrieve and Use Apex Library settings enabled, the content of meta xml file is changed and causes error on deploy.

### Steps To Reproduce:

1.  Enable the 2 settings above
1.  Retrieve a file (say, a visualforce page)
1.  Deploy the file
1.  Get deploy error

### Expected result

File is deployed normally. The meta xml file content usually looks like this
```<?xml version="1.0" encoding="UTF-8"?>
<ApexPage xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>51.0</apiVersion>
    <availableInTouch>false</availableInTouch>
    <confirmationTokenRequired>false</confirmationTokenRequired>
    <label>CaseWorkQueue</label>
</ApexPage>
```

### Actual result

```=== Deploy Errors
PROJECT PATH                                     ERRORS                          
───────────────────────────────────────────────  ────────────────────────────────
force-app/main/default/pages/CaseWorkQueue.page  Required field is missing: label
```

The xml content is now like this
```<?xml version="1.0" encoding="UTF-8"?>
<ApexPage xmlns="http://soap.sforce.com/2006/04/metadata">
	<apiVersion>51.0</apiVersion>
</ApexPage>
```

**VS Code Version**: 1.55.0

**SFDX CLI Version**: sfdx-cli/7.93.0 darwin-x64 node-v15.12.0

**OS and version**: Mac 10.15.7

### PR DESCRIPTION
**Pull request by brpowell**
### What does this PR do?

Fixes #3124 by removing the usage of the tooling api in the new deploy/retrieve. Querying for the metadata xml content with the tooling api is inconsistent across types, incomplete, and is maintenance overhead. It was only used for a small subset of types for single component retrieves. The metadata api is still fast and is safer to use.

### What issues does this PR fix or reference?
#3124 , @W-9110541@

### Functionality Before

Retrieving components such as ApexComponent returned incomplete metadata xml, preventing you from redeploying it later and was a loss of information.

### Functionality After

Metadata xml files are obtained directly from a metadata api call instead.

### CODE REVIEW

File: packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts [hunk 1]
```diff
@@ -210,20 +196,6 @@ export abstract class RetrieveExecutor<T> extends DeployRetrieveExecutor<T> {
...
-    if (components.size === 1 && this.isToolingSupported(oneComponent)) {
-      const projectNamespace = (await SfdxProjectConfig.getValue(
-        'namespace'
-      )) as string;
-      const tooling = new ToolingApi(connection, new MetadataResolver());
-      return tooling.retrieve({
-        components,
-        namespace: projectNamespace
-      });
-    }
```
Comment (brpowell) [inline packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts:225]: Removing the use of single component tooling api retrieves with file paths

File: packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts [hunk 2]
```diff
@@ -281,52 +245,6 @@ export abstract class RetrieveExecutor<T> extends DeployRetrieveExecutor<T> {
     return this.createOutputTable(successes, failures);
   }
 
-  /**
-   * This exists because the Tooling API result currently doesn't conform to the
-   * same interface as the Metadata API deploy and retrieve result objects.
-   */
-  private createToolingOutput(
```
Comment (brpowell) [inline packages/salesforcedx-vscode-core/src/commands/baseDeployRetrieve.ts:288]: Nice to remove special code for this small use case

**Review by AnanyaJha — APPROVED** [review]
